spring:
  application:
    name: KeyCloak-Example
  security:
    ignore-uri: /actuator/**
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/realspeed
          jwk-set-uri: http://localhost:8180/realms/realspeed/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true